[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.1" }
tokio = { version = "1.34.0", features = ["full"] }
serde_json = "1.0.108"

[dev-dependencies]
http-body-util = "0.1.0"
tower = { version = "0.4", features = ["util"] }